name: Docker Build and Push

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
#VERSIONS
          - name: 1.86-alpine-glibc2.34-r0
            context: 1.86/alpine-glibc
            platforms: linux/amd64
            tags: |
              1.86-alpine-glibc
#VERSIONS
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            sirmark/rust
          tags: ${{ matrix.tags }}

      - uses: docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ${{ matrix.context }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: sirmark/rust
